global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: Kafka Streams application
    static_configs:
      - targets: [ 'host.docker.internal:7852' ]
  - job_name: Kafka cluster
    static_configs:
      - targets: [ 'host.docker.internal:1235' ]
  - job_name: Push gateway
    honor_labels: true
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:9091' ]
  - job_name: Schema registry
    static_configs:
      - targets: [ 'host.docker.internal:1236' ]
  - job_name: Kafka lag exporter
    static_configs:
      - targets: [ 'host.docker.internal:8000' ]
  - job_name: ksqlDB
    static_configs:
      - targets: [ 'host.docker.internal:1237' ]
