version: '3.8'
services:

  oauth-provider:
    # https://andifalk.gitbook.io/openid-connect-workshop/bonus-labs/keycloak-test-containers
    volumes:
      - ~/.1config:/host-1config

  # Deprecate it
  zookeeper:

  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_NAME}
      KAFKA_CREATE_TOPICS: "local.audience.version-operations:1:1,local.audience.audiences:1:1:compact"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Monitor it
  schema-registry:
    image: confluentinc/cp-schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_ZK_NAMESPACE: 'schema-registry'

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./dev-resources/monitoring/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro

  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
      - pushgateway
    volumes:
      - ./dev-resources/monitoring/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./dev-resources/monitoring/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./dev-resources/monitoring/dashboard.json:/etc/dashboards/dashboard.json
    ports:
      - 3000:3000
